version: '3.7'

volumes:
    pgdata:
        external: true

services:

    db:
        image: postgres:12.2-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

    adminer:
        image: adminer:latest
        restart: always
        depends_on: 
            - db
        ports:
            - 8081:8080

    redis:
        image: redis:5.0.8-alpine3.11
        restart: always
        ports:
            - 6379:6379

    airflow:
        build: .
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./www/templates:/usr/local/airflow/plugins/templates
            - ./pht_station:/opt/pythonpath/pht_station
            - ./private_key.pem:/opt/private_key.pem # specify local private key path
        environment:
            - LOAD_EX=n      # Do not load example DAGS
            - EXECUTOR=Local
            - POSTGRES_HOST=db
            - PHT_STATION_REGISTY_HOSTNAME=harbor.lukaszimmermann.dev
            - PYTHONPATH=/opt/pythonpath
            - STATION_PRIVATE_KEY_PATH=/opt/private_key.pem
            - STATION_ID=id
            - HARBOR_PW=user_pw
            - HARBOR_USER=username
        depends_on:
          - db
          - redis
        ports:
            - 8080:8080
            - 5555:5555
            - 8793:8793
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
