version: '3.8'
volumes:
  pg_station:
services:
  backend:
    image: ghcr.io/pht-medic/station-api:latest
    container_name: station_backend
    ports:
      - '8000:8000'
    environment:
      - FERNET_KEY=XvKQY_wa9EtUh2j8numvvzKzamXLH4DvVmBAkopYdY4=
      - STATION_DB=postgresql+psycopg2://admin:admin@pg_station/pht_station
      - MINIO_URL=minio:9000
      - MINIO_USER=minio_key
      - MINIO_PW=minio_secret
      - ENVIRONMENT=prod
  frontend:
    image: ghcr.io/pht-medic/station-frontend:latest
    container_name: station_frontend
    ports:
      - '8081:8080'
    environment:
       - STATION_API=http://backend:8000/api
  airflow:
    image: ghcr.io/pht-medic/station-airflow:latest
    container_name: station_airflow
    ports:
      - '8080:8080'
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /path/to/private/key:/opt/private_key.pem
       - /path/to/storage:/opt/station_data
    environment:
       - STATION_ID=1
       - AIRFLOW_DATA_DIR=/opt/station_data
       - STATION_DATA_DIR=/path/to/storage
       - HARBOR_API_URL=https://dev-harbor.grafm.de
       - HARBOR_USER=admin
       - HARBOR_PASSWORD=admin
       - AIRFLOW_USER=admin
       - AIRFLOW_PW=admin
  pg_station:
    image: postgres:14
    container_name: station_db
    ports:
      - '5432:5432'
    volumes:
       - pg_station:/var/lib/postgresql/data
       - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=admin
  minio:
    image: minio/minio:latest
    container_name: station_minio
    ports:
      - '9000:9000'
    environment:
       - MINIO_ACCESS_KEY=minio_key
       - MINIO_SECRET_KEY=minio_secret
