version: '3.7'

volumes:
    pgdata:
        external: true

services:
    db:
        image: postgres:12.1-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

    adminer:
        image: adminer:latest
        restart: always
        depends_on: 
            - db
        ports:
            - 8081:8080
    
    redis:
        image: redis:5.0.7-alpine3.11
        restart: always
        ports: 
            - 6379:6379

    airflow:
        build: .
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_HOST=db
        depends_on:
          - db
          - redis
        ports:
            - 4000:4000
            - 8080:8080
            - 5555:5555
            - 8793:8793
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
