version: '3.7'

volumes:
    pgdata:
        external: true
    mayan_redis:
        external: true
    mayan_media:
        external: true

networks:
  default:
    external:
      name: pht-station

services:

    db:
        image: postgres:12.1-alpine
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

    adminer:
        image: adminer:latest
        restart: always
        depends_on: 
            - db
        ports:
            - 8081:8080
    
    redis:
        image: redis:5.0.7-alpine3.11
        restart: always
        ports: 
            - 6379:6379

    airflow:
        build: .
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_HOST=db
        depends_on:
          - db
          - redis
        ports:
            - 4000:4000
            - 8080:8080
            - 5555:5555
            - 8793:8793
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

##############################################################################################
## Mayan Stuff
##############################################################################################
    mayan:
        depends_on:
            - redis-mayan
            - db
            # Enable to use RabbitMQ
            #- rabbitmq
        environment: &mayan_env
            # Enable to use RabbitMQ
            # MAYAN_CELERY_BROKER_URL: amqp://mayan:mayanrabbitpass@broker:5672/mayan
            # Disable Redis Broker to use RabbitMQ as Broker
            MAYAN_CELERY_BROKER_URL: redis://:mayanredispassword@redis-mayan:6379/0
            MAYAN_CELERY_RESULT_BACKEND: redis://:mayanredispassword@redis-mayan:6379/1
            MAYAN_DATABASES: "{'default':{'ENGINE':'django.db.backends.postgresql','NAME':'mayan','PASSWORD':'mayan-password','USER':'mayan','HOST':'db'}}"
        image: lukaszimmermann/mayanedms:3.3
        ports:
            - "80:8000"
        restart: always
        volumes:
            - mayan_media:/var/lib/mayan

    redis-mayan:
        command:
            - redis-server
            - --databases
            - "2"
            - --maxmemory-policy
            - allkeys-lru
            - --save
            - ""
            - --requirepass mayanredispassword
        image: redis:5.0-alpine
        restart: always
        volumes:
            - mayan_redis:/data
